package testing.helpers;

public enum DestinationCoordinateValidity {

	//Destination coordinate is either valid, or its invalidity reason are one of the below
	VALID_REGULAR, VALID_JUMP, OUTSIDE_OF_THE_BOARD, SAME_AS_SOURCE, NOT_OF_VALID_SQUARE_COLOR, NOT_ORTHOGONAL, OCCUPIED, UNALLOWED_DIRECTION,
	MORE_THAN_TWO_SQUARES_AWAY_FROM_SOURCE, MORE_THAN_ONE_SQUARE_AWAY_FROM_JUMPED_PIECE, NOT_ONE_OF_POSSIBLE_JUMP_MOVES, NOT_THE_BEST_SEQUENCE,
	JUMPED_PIECE_IS_NULL, MULTIPLE_JUMPED_PIECES, JUMPED_PIECE_IS_OWN, PAWN_IN_CROWNHEAD_ILLEGAL_MOVE, OPPOSITE_DIRECTION_OF_LAST_JUMP_MOVE,
	SOURCE_COORDINATE_PROBLEM, UNKNOWN_ERROR
	
}
