package testing.helpers;

public enum SourceCoordinateValidity {
	VALID, OUTSIDE_OF_THE_BOARD, NOT_OF_VALID_SQUARE_COLOR, EMPTY, OPPONENT_PIECE, NOT_THE_PAWN_IN_CROWNHEAD, DIFFERENT_THAN_LAST_JUMP_MOVE_DESTINATION;
}
